permalink: :title-:month:day.html

title: MZAINI30
description: Kumpulan tutorial pemrograman
image: https://telegra.ph/file/4b2b57aa28ed4e3ba1e06.png

url: https://mzaini30.com
telegram_channel: mzaini30bot
email: muhzaini30@gmail.com
disqus: laptopzen

plugins:
  - jekyll-feed

timezone: Asia/Makassar