permalink: :title-:month:day.html

title: Jekyll Pemrograman
description: Kumpulan tutorial pemrograman
image: https://telegra.ph/file/4b2b57aa28ed4e3ba1e06.png

url: https://jekyll-pemrograman.netlify.com
telegram_channel: mzaini30bot
email: muhzaini30@gmail.com
disqus: laptopzen

plugins:
  - jekyll-feed

timezone: Asia/Makassar